# Generated by Django 3.1.6 on 2021-05-25 23:06

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='atracciones',
            fields=[
                ('id_atracciones', models.AutoField(primary_key=True, serialize=False)),
                ('nombre', models.CharField(max_length=100)),
                ('capacidad', models.SmallIntegerField()),
                ('precio', models.DecimalField(decimal_places=20, max_digits=100)),
                ('fecha', models.DateTimeField(max_length=150)),
            ],
        ),
        migrations.CreateModel(
            name='Cliente',
            fields=[
                ('id_cliente', models.AutoField(primary_key=True, serialize=False)),
                ('identificacion', models.IntegerField(unique=True)),
                ('nombre', models.CharField(max_length=50)),
                ('apellido', models.CharField(max_length=50)),
                ('edad', models.IntegerField()),
                ('direccion', models.CharField(max_length=50)),
                ('telefono', models.CharField(max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='empleado',
            fields=[
                ('id_empleado', models.AutoField(primary_key=True, serialize=False)),
                ('nombre', models.CharField(max_length=50)),
                ('apellido', models.CharField(max_length=50)),
                ('correoelectronico', models.EmailField(max_length=100, unique=True)),
                ('identificacion', models.IntegerField(unique=True)),
            ],
        ),
        migrations.CreateModel(
            name='usuario',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('usuario', models.CharField(max_length=50, unique=True)),
                ('correo', models.EmailField(max_length=100, unique=True)),
                ('contraseña', models.CharField(max_length=100, unique=True)),
                ('ROL', models.IntegerField(choices=[(1, 'administrador'), (2, 'cliente'), (3, 'empleado')], default=3)),
            ],
        ),
        migrations.CreateModel(
            name='ventas',
            fields=[
                ('id_ventas', models.AutoField(primary_key=True, serialize=False)),
                ('fecha', models.DateTimeField(max_length=150)),
                ('costo', models.DecimalField(decimal_places=20, max_digits=100)),
                ('cliente', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='aplicacion.cliente')),
            ],
        ),
        migrations.CreateModel(
            name='carrito',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('costo', models.DecimalField(decimal_places=20, max_digits=100)),
                ('cantidad', models.IntegerField()),
                ('total', models.DecimalField(decimal_places=20, max_digits=100)),
                ('carrito_id_atracciones', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='aplicacion.atracciones')),
                ('carrito_id_ventas', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='aplicacion.ventas')),
            ],
        ),
    ]
