# Generated by Django 3.2.4 on 2021-06-16 00:46

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Attractions',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('name', models.CharField(max_length=100)),
                ('capacity', models.SmallIntegerField(default=1)),
                ('price', models.DecimalField(decimal_places=20, max_digits=100)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='Client',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('identificacion', models.PositiveBigIntegerField()),
                ('date_birth', models.DateField()),
                ('address', models.CharField(max_length=150)),
                ('phone', models.PositiveBigIntegerField()),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Sales',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('price', models.DecimalField(decimal_places=20, max_digits=100)),
                ('client', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='aplicacion.client')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='Carrito',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('costo', models.DecimalField(decimal_places=20, max_digits=100)),
                ('cantidad', models.IntegerField()),
                ('total', models.DecimalField(decimal_places=20, max_digits=100)),
                ('attractions', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='aplicacion.attractions')),
                ('sales', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='aplicacion.sales')),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
