# Generated by Django 3.2.4 on 2021-06-16 00:51

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('aplicacion', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Attractions',
            new_name='Attraction',
        ),
        migrations.RenameModel(
            old_name='Sales',
            new_name='Sale',
        ),
    ]
