# Generated by Django 3.2.4 on 2021-07-17 00:45

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('atraccion', '0001_initial'),
        ('usuario', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Carrito',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fecha_creacion', models.DateTimeField(editable=False)),
                ('fecha_actualizacion', models.DateTimeField(editable=False)),
                ('pagado', models.BooleanField(default=False)),
                ('cliente', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='usuario.cliente')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='ItemCarrito',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fecha_creacion', models.DateTimeField(editable=False)),
                ('fecha_actualizacion', models.DateTimeField(editable=False)),
                ('cantidad', models.IntegerField(default=1)),
                ('atraccion', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='atraccion.atraccion')),
                ('carrito', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='venta.carrito')),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
