# Generated by Django 3.2.4 on 2021-06-20 20:34

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Atraccion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fecha_creacion', models.DateTimeField(editable=False)),
                ('fecha_actualizacion', models.DateTimeField(editable=False)),
                ('nombre', models.CharField(max_length=100)),
                ('precio', models.DecimalField(decimal_places=20, max_digits=100)),
                ('estado', models.BooleanField(default=True)),
                ('descripcion', models.CharField(max_length=1200)),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
